const personData = {
    firstName: [
        "Serhii",
        "Denys",
        "Nikita",
        "Alexey",
        "Andreyi",
        "Alexandra",
        "Vasyl",
        "Fedir",
        "Feliks",
        "Taras",
        "Grygoriy",
        "Ihor",
        "Straton",
        "Burian",
        "Dmytro",
        "Mykhaylo",
        "Heorhiy",
        "Demyan",
        "Estas",
        "Yuriy",
        "Borys",
        "Mykola",
        "Kirill",
        "Dymtrus",
        "Boyan",
        "Fedir",
        "Borysko",
        "Symon",
        "Dovud",
        "Pavlo",
        "Makar",
        "Davyd",
        "Maxim",
        "Faddei",
        "Tymofiy",
        "Maksym",
        "Danylo",
        "Lyaksandro",
        "Isai",
        "Umut",
        "Oleksiy",
        "Igor",
        "Andriy",
        "Robin",
        "Arkady",
        "Glib",
        "Antin",
        "Ivan",
        "Bohuslav",
        "Pylyp",
    ],
    lastName: [
        "Balynskyi",
        "Lavrynenko",
        "Ksenchuk",
        "Golovin",
        "Yashin",
        "Chumak",
        "Zaiats",
        "Hryhorenko",
        "Yshchenko",
        "Novak",
        "Eremenko",
        "Zynchenko",
        "Shpak",
        "Lutsenko",
        "Honcharova",
        "Hryshchenko",
        "Samoilenko",
        "Mykhailov",
        "Hlushchenko",
        "Baran",
        "Zaiats",
        "Shcherbyn",
        "Butenko",
        "Honchar",
        "Hordyenko",
        "Kovalev",
        "Zaets",
        "Bondarchuk",
        "Skrypnyk",
        "Makarenko",
        "Boiko",
        "Lukianenko",
        "Voitenko",
        "Vlasyuk",
        "Yvanov",
        "Voznyuk",
        "Pasechnyk",
        "Lytvyn",
        "Tkach",
        "Morozov",
        "Protsenko",
        "Diachenko",
        "Yaremenko",
        "Kovtun",
        "Taran",
        "Vasylev",
        "Semenov",
        "Zayka",
        "Bylyk",
        "Rudenko",
        "Volkov",

    ],
    password: "07033445066aA!",
    country: "Ukraine",
    title: [
        "Senior Full Stack Developer",
        "Front End Expert | React | Javascript",
    ],
    companyData: {
        role: "Senior Full Stack Developer",
        name: "Nitro soft",
        city: "Kyiv",
        startMonth: "January",
        startYear: "2019",
        endMonth: "November",
        endYear: "2022",
        description: `Led architecture, design, and development of 7 new features. 
                    A brand-new admin panel for purchasing agent business, which improved the customer service by 90% and efficiency of operating by
                    25%.
                    Developed 20+ applications following Agile product development methodologies.
                    Oversaw the development and maintenance of new products, technical documentation and workflows`
    },
    educationData: {
        universityName: "Sevastopol National Technical University",
        degree: "Bachelor of Computer Science",
        sector: "IT Science",
        startYear: "2011",
        endYear: "2014",
        description: ""
    },
    englishLvl: "Fluent",
    skills: [
        'React',
        'Next.js',
        'Vue.js',
        'Node',
        'Laravel',
        'Django',
        'Wordpress',
        'Webflow',
        'Javascript',
        'Typescript',
        'Tailwind CSS',
        'Saas',
        'RESTful API',
        'Web UI',
        ],
    summary: "Senior-level full stack developer with 7+ years of experience in web application development. Proven track record in leading and managing software engineering teams. Demonstrated expertise in various web development frameworks, both front-end and back-end",
    street: "Zodchikh Ul., bld. 4, appt. 170",
    city: "kyiv",
    phone: "0442736179",
    hourlyRate: "3",
    avatarUrl: [
        "C:/Avatars/1.jpg",
        "C:/Avatars/2.jpg",
        "C:/Avatars/3.jpeg",
        "C:/Avatars/4.jpg",
    ]

}

module.exports = {
    personData
}
